name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: go test -v ./...

    - name: Go-linter
      # You may pin to the exact commit or the version.
      # uses: Jerome1337/golint-action@c5d17206a0a436bbf1edb91e314ed084f7c57589
      uses: Jerome1337/golint-action@v1.0.2
      #with:
        # Path used by golint command
        #golint-path: # optional, default is ./...
